---
tags: [docker,containers]
projects: [spring-boot]
---
:toc:
:icons: font
:source-highlighter: prettify

== Getting Started

...Queries I had in my mind, when I started learning ...

----
 - How these docker images are built ?
 - Can I build an image of my own ?
 - Can any application just run as a container ?

----

> Let's Start with a hello-world example..

[Source]
```
docker run hello-world
```

= Let's play around with an actual application.

== Introduction to Docker Usecase :

> Clone this Git repository in your machine : https://github.com/Rajeshmohanty23/docker-springboot[Git Repository]
[Source]
----
git clone https://github.com/Rajeshmohanty23/docker-springboot.git
cd docker-springboot
----
 1. Ideally, we create a docker file in order to create a docker image.
Here you can already find already created `Dockerfile` in `docker-springboot/` folder with following content.

`Dockerfile`
[source]
----
FROM openjdk:8-jdk-alpine
EXPOSE 8085
WORKDIR /app
ADD target/*.jar /app/
ENTRYPOINT ["java", "-jar", "docker-sb.jar"]
----

== A Basic Dockerfile

A Spring Boot application is easy to convert into an executable JAR file. All the https://spring.io/guides[Getting Started Guides] do this, and every app that you download from https://start.spring.io[Spring Initializr] will have a build step to create an executable JAR. With Maven you `./mvnw install` . A basic Dockerfile to run that JAR would then look like this, at the top level of your project:

`Dockerfile`
[source]
----
FROM openjdk:8-jdk-alpine
EXPOSE 8085
WORKDIR /app
ADD target/*.jar /app/
ENTRYPOINT ["java", "-jar", "docker-sb.jar"]
----

>3. Then we can simply build an image with following command. Here we are appending `_<corpkey>` to identify the image with a specific tag. Also you can do a `grep` to find your own image easily.

```
$ docker build -t dockersb_<corpkey> .
```

and run it like this:

```
$ docker run -p 8085:8085 dockersb_<corpkey>
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.0.2.RELEASE)

Nov 06, 2018 2:45:16 PM org.springframework.boot.StartupInfoLogger logStarting
INFO: Starting Application v0.1.0 on b8469cdc9b87 with PID 1 (/app.jar started by root in /)
Nov 06, 2018 2:45:16 PM org.springframework.boot.SpringApplication logStartupProfileInfo
...
```

Let's use docker run command to start the container with your built image on port 8085.

```
docker run --network host -p 8085:8085 -d dockersb_<corpkey>
```

You can always push your built docker images to central docker registry [DockerHub]
More info can be found https://docs.docker.com/docker-hub/repos/[Here].

`Dockerfile`
[source]
----
FROM openjdk:8-jdk-alpine
EXPOSE 8085
WORKDIR /app
ADD target/*.jar /app/
ENTRYPOINT ["java", "-jar", "docker-sb.jar"]
----

The `JAR_FILE` could be passed in as part of the `docker` command (it will be different for Maven and Gradle). E.g. for Maven:

```
$ docker build --build-arg JAR_FILE=target/*.jar -t dockersb_<corpkey> .
```


Of course, once you have chosen a build system, you don't need the `ARG` - you can just hard code the jar location. E.g. for Maven:


If you want to poke around inside the image you can open a shell in it like this (the base image does not have `bash`):

```
$ docker run -ti --entrypoint /bin/sh myorg/myapp
/ # ls
app.jar  dev      home     media    proc     run      srv      tmp      var
bin      etc      lib      mnt      root     sbin     sys      usr
/ #
```

NOTE: The alpine base container we used in the example does not have `bash`, so this is an `bash` shell. It has some of the features of `bash` but not all.

If you have a running container and you want to peek into it, use `docker exec` you can do this:

```
$ docker run --name dockersb_<corpkey> -ti --entrypoint /bin/sh dockersb_<corpkey>
$ docker exec -ti dockersb_<corpkey> /bin/sh
/ #
```

where `dockersb_<corpkey>` is the `--name` passed to the `docker run` command. If you didn't use `--name` then docker assigns a mnemonic name which you can scrape from the output of `docker ps`. You could also use the SHA identifier of the container instead of the name, also visible from `docker ps`.

=== The Entry Point

The https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example[exec form] of the Dockerfile `ENTRYPOINT` is used so that there is no shell wrapping the java process. The advantage is that the java process will respond to `KILL` signals sent to the container. In practice that means, for instance, that if you `docker run` your image locally, you can stop it with `CTRL-C`. If the command line gets a bit long you can extract it out into a shell script and `COPY` it into the image before you run it. Example:

`Dockerfile`
[source]
----
FROM openjdk:8-jdk-alpine
VOLUME /tmp
COPY run.sh .
COPY target/*.jar app.jar
ENTRYPOINT ["run.sh"]
----

Remember to use `exec java ...` to launch the java process (so it can handle the `KILL` signals):

`run.sh`
[source]
----
#!/bin/sh
exec java -jar /app.jar
----

Another interesting aspect of the entry point is whether or not you can inject environment variables into the java process at runtime. For example, suppose you want to have the option to add java command line options at runtime. You might try to do this:

`Dockerfile`
[source]
----
FROM openjdk:8-jdk-alpine
VOLUME /app
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","${JAVA_OPTS}","-jar","/app.jar"]
----

and

```
$ docker build -t myorg/myapp .
$ docker run -p 9000:9000 -e JAVA_OPTS=-Dserver.port=9000 myorg/myapp
```

This will fail because the `${}` substitution requires a shell; the exec form doesn't use a shell to launch the process, so the options will not be applied. You can get round that by moving the entry point to a script (like the `run.sh` example above), or by explicitly creating a shell in the entry point. For example:

`Dockerfile`
[source]
----
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app.jar"]
----

You can then launch this app with

Using an `ENTRYPOINT` with an explicit shell like the above means that you can pass environment variables into the java command, but so far you cannot also provide command line arguments to the Spring Boot application. This trick doesn't work to run the app on port 9000:

```
$ docker run -p 9000:9000 myorg/myapp --server.port=9000
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.0.RELEASE)
...
2019-10-29 09:20:19.718  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 8080
```

The reason it didn't work is because the docker command (the `--server.port=9000` part) is passed to the entry point (`sh`), not to the java process which it launches. To fix that you need to add the command line from the `CMD` to the `ENTRYPOINT`:

`Dockerfile`
[source]
----
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar /app.jar ${0} ${@}"]
----

```
$ docker run -p 9000:9000 myorg/myapp --server.port=9000
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.0.RELEASE)
...
2019-10-29 09:30:19.751  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port(s): 9000
```

Note the use of `${0}` for the "command" (in this case the first program argument) and `${@}` for the "command arguments" (the rest of the program arguments). If you use a script for the entry point, then you don't need the `${0}` (that would be `/app/run.sh` in the example above). Example:

`run.sh`
[source]
----
#!/bin/sh
exec java ${JAVA_OPTS} -jar /app.jar ${@}
----

The docker configuration is very simple so far, and the generated image is not very efficient. The docker image has a single filesystem layer with the fat jar in it, and every change we make to the application code changes that layer, which might be 10MB or more (even as much as 50MB for some apps). We can improve on that by splitting the JAR up into multiple layers.

=== Smaller Images

Notice that the base image in the example above is `openjdk:8-jdk-alpine`. The `alpine` images are smaller than the standard `openjdk` library images from https://hub.docker.com/_/openjdk/[Dockerhub]. There is no official alpine image for Java 11 yet (AdoptOpenJDK had one for a while but it no longer appears on their https://hub.docker.com/r/adoptopenjdk/openjdk11/[Dockerhub page]). You can also save about 20MB in the base image by using the "jre" label instead of "jdk". Not all apps work with a JRE (as opposed to a JDK), but most do, and indeed some organizations enforce a rule that every app has to because of the risk of misuse of some of the JDK features (like compilation).

Another trick that could get you a smaller image is to use https://openjdk.java.net/projects/jigsaw/quick-start#linker[JLink], which is bundled with OpenJDK 11. JLink allows you to build a custom JRE distribution from a subset of modules in the full JDK, so you don't need a JRE or JDK in the base image. In principle this would get you a smaller total image size than using the `openjdk` official docker images. In practice, you won't (yet) be able to use the `alpine` base image with JDK 11, so your choice of base image will be limited and will probably result in a larger final image size. Also, a custom JRE in your own base image cannot be shared amongst other applications, since they would need different customizations. So you might have smaller images for all your applications, but they still take longer to start because they don't benefit from caching the JRE layer.

That last point highlights a really important concern for image builders: the goal is not necessarily always going to be to build the smallest image possible. Smaller images are generally a good idea because they take less time to upload and download, but only if none of the layers in them are already cached. Image registries are quite sophisticated these days and you can easily lose the benefit of those features by trying to be clever with the image construction. If you use common base layers, the total size of an image is less of a concern, and will probably become even less of one as the registries and platforms evolve. Having said that, it is still important, and useful, to try and optimize the layers in our application image, but the goal should always be to put the fastest changing stuff in the highest layers, and to share as many of the large, lower layers as possible with other applications.

== A Better Dockerfile

A Spring Boot fat jar naturally has "layers" because of the way that the jar itself is packaged. If we unpack it first it will already be divided into external and internal dependencies. To do this in one step in the docker build, we need to unpack the jar first. For example (sticking with Maven, but the Gradle version is pretty similar):

```
$ mkdir target/dependency
$ (cd target/dependency; jar -xf ../*.jar)
$ docker build -t myorg/myapp .
```

with this `Dockerfile`

`Dockerfile`
[source]
----
FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","hello.Application"]
----

There are now 3 layers, with all the application resources in the later 2 layers. If the application dependencies don't change, then the first layer (from `BOOT-INF/lib`) will not change, so the build will be faster, and so will the startup of the container at runtime as long as the base layers are already cached.

NOTE: We used a hard-coded main application class `hello.Application`. This will probably be different for your application. You could parameterize it with another `ARG` if you wanted. You could also copy the Spring Boot fat `JarLauncher` into the image and use it to run the app - it would work and you wouldn't need to specify the main class, but it would be a bit slower on startup.


== Multi-Stage Build

The `Dockerfile` above assumed that the fat JAR was already built on the command line. You can also do that step in docker using a multi-stage build, copying the result from one image to another. Example, using Maven:

`Dockerfile`
[source]
----
FROM openjdk:8-jdk-alpine as build
WORKDIR /workspace/app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN ./mvnw install -DskipTests
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","hello.Application"]
----

The first image is labelled "build" and it is used to run Maven and build the fat jar, then unpack it. The unpacking could also be done by Maven or Gradle (this is the approach taken in the Getting Started Guide) - there really isn't much difference, except that the build configuration would have to be edited and a plugin added.

Notice that the source code has been split into 4 layers. The later layers contain the build configuration and the source code for the app, and the earlier layers contain the build system itself (the Maven wrapper). This is a small optimization, and it also means that we don't have to copy the `target` directory to a docker image, even a temporary one used for the build.

Every build where the source code changes will be slow because the Maven cache has to be re-created in the first `RUN` section. But you have a completely standalone build that anyone can run to get your application running as long as they have docker. That can be quite useful in some environments, e.g. where you need to share your code with people who don't know Java.

== Security Aspects

Just as in classic VM-deployments, processes should not be run with root permissions. Instead the image should contain a non-root user that runs the app.

In a `Dockerfile`, this can be achieved by adding another layer that adds a (system) user and group, then set it as the current user (instead of the default, root):

`Dockerfile`
[source]
----
FROM openjdk:8-jdk-alpine

RUN addgroup -S demo && adduser -S demo -G demo
USER demo

...
----

In case someone manages to break out of your app and run system commands inside the container, this will limit their capabilities (principle of least privilege).

NOTE: Some of the further `Dockerfile` commands only work as root, so maybe you have to move the USER command further down (e.g. if you plan to install more packages into the container, which only works as root).

NOTE: Other approaches, not using a `Dockerfile`, might be more amenable. For instance, in the buildpack approach described later, most implementations will use a non-root user by default.

Another consideration is that the full JDK is probably not needed by most apps at runtime, so we can safely switch to the JRE base image, once we have a multi-stage build. So in the multi-stage build above we can use

`Dockerfile`
[source]
----
FROM openjdk:8-jre-alpine

...
----

for the final, runnable image. As already mentioned above, this also saves some space in the image which would be occupied by tools that are not needed at runtime.
